"""Check handbook prose against the project style rules.

Sentence length, banned filler, and the terminology rules from
.claude/skills/lst-style/. Code blocks, tables and generated pages are skipped.

Exit 1 on any banned word. Long sentences warn but do not fail.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

BANNED = [
    "simply", "just simply", "easily", "obviously", "of course", "leverage",
    "delve", "seamless", "seamlessly", "robust", "powerful", "comprehensive",
    "it's important to note", "it is important to note", "in order to",
    "please note", "as we can see", "let's dive in", "needless to say",
    "utilize", "plethora", "myriad", "elegant",
]

MAX_WORDS = 25

SENT = re.compile(r"(?<=[.!?])\s+")


def strip_noise(text):
    """Remove front matter, code fences, tables, admonition markers, HTML comments."""
    text = re.sub(r"\A---\n.*?\n---\n", "", text, flags=re.S)
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    text = re.sub(r"^\|.*$", "", text, flags=re.M)        # tables
    # Each bullet is its own unit. Removing the marker outright would glue a run of
    # short bullets into one very long "sentence".
    text = re.sub(r"^\s*[-*+]\s+", "\n\n", text, flags=re.M)
    text = re.sub(r"^#{1,6}\s+.*$", "", text, flags=re.M)  # headings
    text = re.sub(r"`[^`]*`", "X", text)                   # inline code
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)   # links
    text = re.sub(r"^\s*!!!.*$", "", text, flags=re.M)     # admonition openers
    # Emphasis markers hide sentence ends: "**Done.** Next" must split at the period.
    text = re.sub(r"\*\*([^*]*)\*\*", r"\1", text)
    text = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"\1", text)
    return text


def main():
    fails, warns, pages = [], [], 0
    for md in sorted(DOCS.rglob("*.md")):
        raw = md.read_text(encoding="utf-8")
        if "GENERATED by tools/" in raw:
            continue
        pages += 1
        rel = md.relative_to(ROOT)
        body = strip_noise(raw)

        low = body.lower()
        for word in BANNED:
            for m in re.finditer(r"\b" + re.escape(word) + r"\b", low):
                ctx = body[max(0, m.start() - 30):m.start() + 40].replace("\n", " ")
                fails.append((rel, word, ctx.strip()))

        for para in body.split("\n\n"):
            para = " ".join(para.split())
            if not para:
                continue
            for s in SENT.split(para):
                n = len(s.split())
                if n > MAX_WORDS:
                    warns.append((rel, n, s[:80]))

    print("checked %d hand-written pages" % pages)

    if warns:
        print("\n%d long sentence(s) over %d words:" % (len(warns), MAX_WORDS))
        for rel, n, s in warns[:12]:
            print("  %s  (%d words)" % (rel, n))
            print("      %s..." % s)

    if fails:
        print("\n%d banned word(s):" % len(fails))
        for rel, word, ctx in fails:
            print("  %s  '%s'" % (rel, word))
            print("      ...%s..." % ctx)
        return 1

    print("no banned words")
    return 0


if __name__ == "__main__":
    sys.exit(main())
