"""Generate docs/outputsheets/token-index.md from work/output-tokens.json.

Every output token PCGen implements on the pinned commit, read from the classes that
declare them. Argument syntax is not here, because no output token declares it in a
form anything can read. See the page text.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "work" / "output-tokens.json"
OUT = ROOT / "docs" / "outputsheets" / "token-index.md"
GH = "https://github.com/PCGen/pcgen/blob"


def main():
    d = json.loads(DATA.read_text(encoding="utf-8"))
    sha, ver = d["pinned_sha"], d["pcgen_version"]
    tokens = d["tokens"]
    models = d["freemarker_models"]

    current = [t for t in tokens if not t["deprecated"]]
    dead = [t for t in tokens if t["deprecated"]]

    def link(t):
        return "[`%s`](%s/%s/%s)" % (t["class"], GH, sha, t["path"])

    L = []
    L.append("---")
    L.append("title: Output token index")
    L.append("---")
    L.append("")
    L.append("# Output token index")
    L.append("")
    L.append("<!-- GENERATED by tools/gen_output_index.py - do not edit by hand -->")
    L.append("")
    L.append("Every output token PCGen implements, read from the classes that declare")
    L.append("them. PCGen `%s`, commit [`%s`](%s/tree/%s)."
             % (ver, sha[:8], GH.rsplit("/", 1)[0], sha))
    L.append("")
    L.append("**%d tokens**, of which %d are deprecated." % (len(tokens), len(dead)))
    L.append("")
    L.append("!!! warning \"These are not LST tags\"")
    L.append("    An LST tag is read from a data file. An output token is written in a")
    L.append("    character sheet template and reads a value back out of a finished")
    L.append("    character. Different system, different classes. For LST tags see the")
    L.append("    [tag index](../lst/reference/tag-index.md).")
    L.append("")
    L.append("## What this index does not carry")
    L.append("")
    L.append("Argument syntax. A marker such as `|STAT.0.MOD|` is one token name and two")
    L.append("arguments, and the arguments exist only inside the token's own parsing code.")
    L.append("There is no sub-token registry to read, so nothing can enumerate them.")
    L.append("")
    L.append("Use this index to answer *does this token exist, and where is it")
    L.append("implemented*. Read the class for what it accepts. See")
    L.append("[output and saving](../internals/output-and-saving.md).")
    L.append("")
    L.append("## Tokens")
    L.append("")
    L.append("`core` tokens are registered directly by the export handler. `plugin`")
    L.append("tokens arrive through the plugin jars, the same way LST tags do.")
    L.append("")
    L.append("| Token | Registered | Class |")
    L.append("|---|---|---|")
    for t in current:
        L.append("| `%s` | %s | %s |" % (t["token"], t["origin"], link(t)))
    L.append("")
    L.append("## Deprecated")
    L.append("")
    L.append("These sit in a `deprecated` package. Nothing in the source names a")
    L.append("replacement, and no deprecation message is logged, so the package is the")
    L.append("only signal. Treat them as present but not to be used in new sheets.")
    L.append("")
    L.append("| Token | Class |")
    L.append("|---|---|")
    for t in dead:
        L.append("| `%s` | %s |" % (t["token"], link(t)))
    L.append("")
    L.append("## FreeMarker model keys")
    L.append("")
    L.append("A FreeMarker sheet does not use the tokens above directly. It reads a data")
    L.append("model, and these are its top-level keys, collected from where each is")
    L.append("registered.")
    L.append("")
    L.append("| Key | Registered in |")
    L.append("|---|---|")
    for m in models:
        L.append("| `%s` | `%s` |" % (m["key"], m["registered_in"]))
    L.append("")
    L.append("## Related")
    L.append("")
    L.append("- [Output and saving](../internals/output-and-saving.md) - how a sheet is run")
    L.append("- [Tag index](../lst/reference/tag-index.md) - the other system")
    L.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L), encoding="utf-8")
    print("%d tokens (%d deprecated), %d model keys -> %s"
          % (len(tokens), len(dead), len(models), OUT.relative_to(ROOT)))


if __name__ == "__main__":
    main()
