"""Generate docs/lst/reference/tag-index.md from work/tokens.json.

Covers every tag PCGen implements on the pinned commit. Hand-written detail pages
live beside this under reference/tags/ and are linked from here when they exist.
"""
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "work" / "tokens.json"
OUT = ROOT / "docs" / "lst" / "reference" / "tag-index.md"
TAGS_DIR = OUT.parent / "tags"
GH = "https://github.com/PCGen/pcgen/blob"

FAMILY_TITLE = {
    "lst": "Data and game mode tags",
    "pre": "Prerequisites (`PRExxx`)",
    "bonus": "Bonuses (`BONUS:`)",
    "primitive": "Primitives",
    "qualifier": "Qualifiers",
    "modifier": "Modifiers",
}

FAMILY_BLURB = {
    "lst": "Tags written in `.lst` and `.pcc` files. The **Applies to** column is the "
           "object type that accepts the tag, taken from `getTokenClass()`.",
    "pre": "Conditions that gate whether something applies. Valid on most objects.",
    "bonus": "Numeric and list modifiers, written as `BONUS:<name>|...`.",
    "primitive": "Selectors used inside `CHOOSE:` and similar tags.",
    "qualifier": "Filters such as `QUALIFIED[...]` used inside choosers.",
    "modifier": "Operators used by the formula system.",
}


def main():
    d = json.loads(DATA.read_text(encoding="utf-8"))
    sha, ver = d["pinned_sha"], d["pcgen_version"]
    tokens = d["tokens"]

    written = {p.stem.upper() for p in TAGS_DIR.glob("*.md")} if TAGS_DIR.exists() else set()

    by_family = defaultdict(lambda: defaultdict(list))
    for t in tokens:
        by_family[t["family"]][t["full_tag"]].append(t)

    uniq = len({t["full_tag"] for t in tokens})
    dep = len({t["full_tag"] for t in tokens if t["deprecated"]})

    L = []
    L.append("---")
    L.append("title: Tag index")
    L.append("---")
    L.append("")
    L.append("# Tag index")
    L.append("")
    L.append("<!-- GENERATED by tools/gen_index.py. Do not edit by hand. -->")
    L.append("")
    L.append("Every tag PCGen implements, read from the token classes in the source.")
    L.append("")
    L.append("!!! info \"What this is built from\"")
    L.append("    PCGen `%s`, commit [`%s`](%s/%s)." % (ver, sha[:12], GH.replace("/blob", "/tree"), sha))
    L.append("")
    L.append("    %d tags, %d of them deprecated. Generated, not hand-written, so it" % (uniq, dep))
    L.append("    matches the code rather than the published docs.")
    L.append("")
    L.append("Tags with a linked name have a full page. The rest list what the code says:")
    L.append("what accepts them, and the class that implements them.")
    L.append("")

    for fam in ["lst", "pre", "bonus", "primitive", "qualifier", "modifier"]:
        groups = by_family.get(fam)
        if not groups:
            continue
        L.append("## %s" % FAMILY_TITLE[fam])
        L.append("")
        L.append(FAMILY_BLURB[fam])
        L.append("")
        L.append("| Tag | Applies to | Implemented by | Status |")
        L.append("|---|---|---|---|")
        for tag in sorted(groups):
            rows = groups[tag]
            applies = ", ".join(sorted({r["applies_to"] or "any" for r in rows}))
            if len(applies) > 60:
                applies = applies[:57] + "..."
            first = rows[0]
            link = "[`%s`](tags/%s.md)" % (tag, tag.lower().replace(":", "-")) \
                if tag.upper() in written else "`%s`" % tag
            classes = sorted({r["class"] for r in rows})
            cls = "[`%s`](%s/%s/%s)" % (classes[0], GH, sha, first["source"])
            if len(classes) > 1:
                cls += " +%d" % (len(classes) - 1)
            if any(r["deprecated"] for r in rows):
                v = next((r["deprecated_version"] for r in rows if r["deprecated_version"]), None)
                status = "deprecated (%s)" % v if v else "deprecated"
            else:
                status = ""
            L.append("| %s | %s | %s | %s |" % (link, applies, cls, status))
        L.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L), encoding="utf-8")
    print("wrote %s" % OUT)
    print("  %d unique tags, %d deprecated, %d with detail pages" % (uniq, dep, len(written)))


if __name__ == "__main__":
    main()
