"""Detect when PCGen has changed under the handbook.

Clones PCGen at current master, rescans the token classes, and diffs against the
committed tags.json. Reports tags added, removed, or changed, and names the pages
citing them.

Run weekly by .github/workflows/drift.yml. Also runnable by hand:

    python tools/ingest.py --report drift.md
"""
import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
COMMITTED = ROOT / "tags.json"
REPO = "https://github.com/PCGen/pcgen.git"

SPARSE = [
    "code/src/java", "code/src/test", "code/src/slowtest",
    "docs", "data/zen_test", "data/35e/homebrew", "system/gameModes",
]


def run(cmd, cwd=None):
    return subprocess.run(cmd, cwd=cwd, check=True, capture_output=True, text=True)


def clone(dest):
    run(["git", "clone", "--depth", "1", "--filter=blob:none", "--sparse", REPO, str(dest)])
    run(["git", "sparse-checkout", "set"] + SPARSE, cwd=dest)
    return run(["git", "rev-parse", "HEAD"], cwd=dest).stdout.strip()


def scan_into(src_dir):
    """Re-run the scanner against an arbitrary checkout."""
    work = ROOT / "work"
    work.mkdir(exist_ok=True)
    backup = None
    live = work / "pcgen-src"
    # Already scanning the live checkout: just run the scanner in place.
    if live.exists() and Path(src_dir).resolve() == live.resolve():
        run([sys.executable, str(ROOT / "tools" / "scan_tokens.py")])
        return json.loads((work / "tokens.json").read_text(encoding="utf-8"))
    if live.exists():
        backup = work / "pcgen-src.ingest-backup"
        if backup.exists():
            import shutil
            shutil.rmtree(backup, ignore_errors=True)
        live.rename(backup)
    try:
        os.symlink(src_dir, live, target_is_directory=True)
    except (OSError, NotImplementedError):
        import shutil
        shutil.copytree(src_dir, live)
    try:
        sha_file = ROOT / "PCGEN-SHA"
        old_sha = sha_file.read_text(encoding="utf-8")
        run([sys.executable, str(ROOT / "tools" / "scan_tokens.py")])
        fresh = json.loads((work / "tokens.json").read_text(encoding="utf-8"))
        sha_file.write_text(old_sha, encoding="utf-8")
        return fresh
    finally:
        if live.is_symlink():
            live.unlink()
        elif live.exists():
            import shutil
            shutil.rmtree(live, ignore_errors=True)
        if backup and backup.exists():
            backup.rename(live)


def key(t):
    """A unique identity for one registration.

    The implementing class belongs in the key. Ten (tag, applies_to) pairs have
    more than one registration - ADD on CDOMObject has three, one current and
    two deprecated - so without the class the dict below keeps whichever the
    filesystem happened to yield last. That reported ADD and DOMAIN as changed
    every week for a fortnight while nothing upstream had moved.

    The source path is the identity, not the class name: three different
    qualifier packages each hold an EquipmentToken, and two hold a ClassToken.

    A moved or renamed class now shows as a removal plus an addition rather than
    a change, which is the honest description of it.
    """
    return (t["full_tag"], t["applies_to"] or "any", t["source"])


def citing_pages(tag):
    """Pages that mention this tag, so a drift report says what to review."""
    hits = []
    pat = re.compile(r"\b" + re.escape(tag) + r"\b")
    for md in sorted(DOCS.rglob("*.md")):
        if "GENERATED by tools/" in md.read_text(encoding="utf-8"):
            continue
        if pat.search(md.read_text(encoding="utf-8")):
            hits.append(str(md.relative_to(ROOT)).replace("\\", "/"))
    return hits


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", default=None, help="write a markdown report here")
    ap.add_argument("--src", default=None, help="use an existing checkout instead of cloning")
    args = ap.parse_args()

    if not COMMITTED.exists():
        sys.exit("tags.json missing - run tools/scan_tokens.py first")
    old = json.loads(COMMITTED.read_text(encoding="utf-8"))

    if args.src:
        new_sha = run(["git", "rev-parse", "HEAD"], cwd=args.src).stdout.strip()
        fresh = scan_into(Path(args.src))
    else:
        with tempfile.TemporaryDirectory() as td:
            dest = Path(td) / "pcgen"
            new_sha = clone(dest)
            fresh = scan_into(dest)

    o = {key(t): t for t in old["tokens"]}
    n = {key(t): t for t in fresh["tokens"]}

    added = sorted(set(n) - set(o))
    removed = sorted(set(o) - set(n))
    changed = sorted(
        k for k in set(o) & set(n)
        if (o[k]["deprecated"], o[k]["class"]) != (n[k]["deprecated"], n[k]["class"])
    )

    total = len(added) + len(removed) + len(changed)
    summary = "%d added, %d removed, %d changed" % (len(added), len(removed), len(changed))

    print("handbook pinned at %s" % old["pinned_sha"][:12])
    print("upstream master at %s" % new_sha[:12])
    print(summary)

    if args.report:
        L = ["# Upstream drift", ""]
        L.append("Handbook is pinned at `%s` (PCGen %s)." % (old["pinned_sha"][:12], old["pcgen_version"]))
        L.append("Upstream `master` is now `%s` (PCGen %s)." % (new_sha[:12], fresh["pcgen_version"]))
        L.append("")
        L.append("**%s**" % summary)
        L.append("")
        for title, items in [("Removed", removed), ("Added", added), ("Changed", changed)]:
            if not items:
                continue
            L.append("## %s" % title)
            L.append("")
            for k in items[:60]:
                tag, applies = k
                pages = citing_pages(tag) if title != "Added" else []
                note = "  — cited by %s" % ", ".join("`%s`" % p for p in pages) if pages else ""
                L.append("- `%s` (%s)%s" % (tag, applies, note))
            if len(items) > 60:
                L.append("- ...and %d more" % (len(items) - 60))
            L.append("")
        L.append("## To update")
        L.append("")
        L.append("```sh")
        L.append("echo %s > PCGEN-SHA" % new_sha)
        L.append("python tools/scan_tokens.py")
        L.append("python tools/gen_index.py")
        L.append("python tools/check_examples.py")
        L.append("```")
        L.append("")
        L.append("Then review the pages named above and append to `log.md`.")
        Path(args.report).write_text("\n".join(L), encoding="utf-8")
        print("report -> %s" % args.report)

    out = os.environ.get("GITHUB_OUTPUT")
    if out:
        with open(out, "a", encoding="utf-8") as f:
            f.write("changed=%s\n" % ("true" if total else "false"))
            f.write("summary=%s\n" % summary)
    return 0


if __name__ == "__main__":
    sys.exit(main())
