"""Coherence checks the other tools do not cover.

mkdocs --strict catches dead links and bad nav entries. check_examples.py catches
wrong tags. This catches the rest:

  - pages nothing links to
  - pages missing from the nav
  - source citations pointing at a file that no longer exists
  - hand-written pages missing the sections WIKI-SCHEMA.md requires

Exit 1 on a broken citation or an orphan. Everything else warns.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
SRC = ROOT / "work" / "pcgen-src"
MKDOCS = ROOT / "mkdocs.yml"

LINK = re.compile(r"\[[^\]]*\]\(([^)#]+\.md)(?:#[^)]*)?\)")
# Both citation forms from WIKI-SCHEMA.md: visible links and hidden comments.
CITE = re.compile(r"(?:blob/[0-9a-f]+/|src:\s*)((?:code|data|system|PCGen-\w+)/[\w./-]+\.\w+)")
GENERATED = "GENERATED by tools/"

# Sections a page type must have, by directory.
REQUIRED = {
    "lst/files": ["## Gotchas", "## Related"],
    "lst/howto": ["## Related"],
    "lst/concepts": ["## Related"],
    "internals": ["## Related"],
}


# One fact, one owner. A claim explained on five pages goes stale on four of
# them. Other pages may name the subject and link to the owner; they may not
# re-explain it.
OWNED = [
    ("duplicate keys resolve by SOURCEDATE", "lst/concepts/keys-and-names.md",
     r"(?i)(newer|later)[^.]{0,40}SOURCEDATE|SOURCEDATE[^.]{0,40}(wins|survives)"
     r"|first (one )?loaded wins"),
    ("datatest skips a PCC without SHOWINMENU", "internals/testing.md",
     r"(?i)datatest[^.]{0,60}(skip|silen)|(skip|silen)[^.]{0,60}SHOWINMENU"),
    ("the PCC FEAT tag is deprecated", "appendix/whats-changed.md",
     r"(?i)`FEAT:`[^.]{0,50}deprecat|deprecat[^.]{0,50}`FEAT:`"),
    ("dots in a TYPE match mean and, not or", "lst/concepts/types.md",
     r"(?i)dots?[^.]{0,40}TYPE[^.]{0,40}mean[^.]{0,25}and"
     r"|every listed type must[^.]{0,25}(match|present)"),
    ("BONUS:VAR applies only to a declared variable", "lst/concepts/declaring-variables.md",
     r"(?i)BONUS:VAR[^.]{0,60}(only|not)[^.]{0,40}(declar|DEFINE)"
     r"|(without|no) [^.]{0,20}DEFINE[^.]{0,40}BONUS:VAR[^.]{0,40}(nothing|ignored|skipped)"),
]


def owned_facts(pages, docs):
    """Pages other than the owner that re-explain a fact they do not own."""
    out = []
    for fact, owner, pattern in OWNED:
        rx = re.compile(pattern)
        for p in pages:
            rel = str(p.relative_to(docs)).replace(chr(92), "/")
            if rel == owner:
                continue
            text = p.read_text(encoding="utf-8")
            if GENERATED in text:
                continue
            m = rx.search(text)
            if m:
                out.append((rel, fact, owner, m.group(0)[:60]))
    return out


def nav_paths():
    if not MKDOCS.exists():
        return set()
    text = MKDOCS.read_text(encoding="utf-8")
    nav = text.split("\nnav:", 1)[-1]
    return set(re.findall(r"([\w/-]+\.md)", nav))


def main():
    pages = sorted(DOCS.rglob("*.md"))
    rel = {str(p.relative_to(DOCS)).replace("\\", "/") for p in pages}
    nav = nav_paths()

    linked = set()
    bad_cites = []
    missing_sections = []
    checked_cites = 0

    for p in pages:
        text = p.read_text(encoding="utf-8")
        here = p.relative_to(DOCS).parent

        for target in LINK.findall(text):
            if target.startswith(("http://", "https://")):
                continue
            resolved = (here / target).as_posix()
            resolved = str(Path(resolved).as_posix()).replace("\\", "/")
            # normalise ../ segments
            parts = []
            for seg in resolved.split("/"):
                if seg == "..":
                    if parts:
                        parts.pop()
                elif seg not in (".", ""):
                    parts.append(seg)
            linked.add("/".join(parts))

        if GENERATED in text:
            continue

        for path in CITE.findall(text):
            checked_cites += 1
            if SRC.exists() and not (SRC / path).exists():
                bad_cites.append((p.relative_to(ROOT), path))

        key = here.as_posix()
        for prefix, needed in REQUIRED.items():
            if key == prefix:
                for section in needed:
                    if section not in text:
                        missing_sections.append((p.relative_to(ROOT), section))

    trespass = owned_facts(pages, DOCS)

    orphans = sorted(r for r in rel if r not in linked and r != "index.md")
    not_in_nav = sorted(r for r in rel if r not in nav)

    print("pages: %d   internal links: %d   citations checked: %d"
          % (len(pages), len(linked), checked_cites))
    if not SRC.exists():
        print("NOTE: no source checkout, citation paths not verified")

    fail = False

    if bad_cites:
        fail = True
        print("\n%d citation(s) pointing at a file that does not exist:" % len(bad_cites))
        for page, path in bad_cites:
            print("  %s" % page)
            print("      %s" % path)

    if orphans:
        fail = True
        print("\n%d orphan page(s) - nothing links to them:" % len(orphans))
        for o in orphans:
            print("  %s" % o)

    if not_in_nav:
        print("\n%d page(s) not in the nav:" % len(not_in_nav))
        for n in not_in_nav:
            print("  %s" % n)

    if missing_sections:
        print("\n%d page(s) missing a section WIKI-SCHEMA.md requires:" % len(missing_sections))
        for page, section in missing_sections:
            print("  %-46s %s" % (page, section))

    if trespass:
        print("")
        print("%d page(s) re-explaining a fact another page owns:" % len(trespass))
        for page, fact, owner, hit in trespass:
            print("  %s" % page)
            print("      %s -> owned by %s" % (fact, owner))
            print("      matched: %s" % hit)

    if not fail and not not_in_nav and not missing_sections and not trespass:
        print("clean")
    return 1 if fail else 0


if __name__ == "__main__":
    sys.exit(main())
